package gsg.gae.core.ps.service;

import gsg.gae.core.common.objectify.service.OfyService;
import gsg.gae.core.ps.domain.PS;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.stereotype.Service;

import java.util.Date;
import java.util.List;

@Service
public class PSServiceImpl implements PSService{

	@Autowired
	@Qualifier("objectifyService")
	OfyService objectifyService;

	@Override
	public PS save(PS ps) {
		objectifyService.ofy().save().entity(ps).now();
		return ps;
	}

	@Override
	public List<PS> get() {
		return objectifyService.ofy().load().type(PS.class).list();
	}

	@Override
	public List<PS> getByUserId(Long id) {
		return null;
	}

	@Override
	public PS getById(Long id) {
		return objectifyService.ofy().load().type(PS.class).id(id).now();
	}

	@Override
	public void delete(Long id) {

	}

	@Override
	public PS createEmptyPS(Long userId) {

		PS ps = new PS();
		ps.setStatus("tmp");
		ps.setDate(new Date());
		ps.setUserId(userId);
		objectifyService.ofy().save().entity(ps).now();
		/*assert ps.id != null;    // id was autogenerated
		objectifyService.ofy().load().type(PS.class).id(ps.getId()).now();*/
		System.out.println("\nFUCKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK: " + ps.getId());

		return ps;
	}

}
